### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by Ale0311** [mileyan/pseudo-LiDAR_e2e#11]
Hello!

I am trying to train PointRCNN and I followed all the steps mentioned in the README files. However, I get the following error:

![image](https://user-images.githubusercontent.com/34925696/95419345-1fbe7880-0942-11eb-9e1f-f01a8bfb86f0.png)

and before that, I get this:

![image](https://user-images.githubusercontent.com/34925696/95419394-3bc21a00-0942-11eb-9a89-da4deefe055d.png)

I tries running the whole process on the CPU, for a more detailed error stack, but nothing happened because I waited for more than a day and the training hadn't even started.

Do you have any idea why this happens? I looked it up and I couldn't find any conclusive answer.

**Comment by rui1996** [comment]
Hi can you share the pytorch version you used?  The code is developed under pytorch 1.1.0.
Though I have not encountered this when I use this code, I think it is probably because the interface between pytorch and GPU has been changed.

**Comment by Ale0311** [comment]
**EDIT**: I think it's because of torch-scatter. What version did you use?
Now the smallest version available is for pytorch 1.4.0. There isn't any compatible version for pytorch 1.1.0. Can this be the issue?

Thanks for your response!

I am using pytorch 1.4.0. I tried creating a new environment using version 1.1.0, but I get this assertion error: 
**RuntimeError: Expected PyTorch version 1.4 but found version 1.1.**

Why would I get this error if the version of pytorch I need to use is 1.1.0?

Thanks in advance.

**Comment by Ale0311** [comment]
I finally fixed it. Thanks for your suggestion regarding pytorch version. I installed torch-scatter 1.3.0, which works with pytorch 1.1.0.

`pip install torch-scatter==1.3.1`
