### ISSUE TITLE
About the location of the code

### ISSUE THREAD

**Issue by jiangchaokang** [mileyan/pseudo-LiDAR_e2e#15]
May I ask where the 'Change of Representation' module of the paper is reflected in e2e (RCNN)?
Where is the interface between point cloud and 3D object detection in the code(e2e_RCNN)?
I can't find it at the moment. Can you give me a hint?
Thank you very much!

**Comment by XiangZhou1** [comment]
Hi, do you know  where the 'Change of Representation' module of the paper in e2e (PIXOR)?  I cannot found it either.

**Comment by rui1996** [comment]
Hi, please refer here: https://github.com/mileyan/pseudo-LiDAR_e2e/blob/master/PointRCNN/lib/net/depth_net.py#L152
