### ISSUE TITLE
CUDA Version

### ISSUE THREAD

**Issue by shuxiusuxiu** [mileyan/pseudo-LiDAR_e2e#16]
Hello, thank you for your works. I encountered a problem when stepping into pointnet2.furthest_point_sampling_wrapper. It returned all zeros. I thought it might be caused by CUDA. I'd be appreciated if you could help me.

**Comment by rui1996** [comment]
Hi, I guess this sort of problems mostly come from the difference of environment, like pytorch and cuda version, please refer to the readme as well as the original pointrcnn repo for assistance.
