### ISSUE TITLE
How to view APbev/AP3D in the results

### ISSUE THREAD

**Issue by Wyx9352** [mileyan/pseudo-LiDAR_e2e#17]
Why is there no AP3D in this “outputs_07.txt” file?

Thank you for participating in our evaluation!
Loading detections...
number of files for evaluation: 3769
  done.
save ./saves/pixor_e2e/predicted_label_eval/plot/car_detection.txt
car_detection AP: 0.000000 0.000000 0.000000
Finished 2D bounding box eval.
Going to eval ground for class: car
save ./saves/pixor_e2e/predicted_label_eval/plot/car_detection_ground.txt
car_detection_ground AP: 77.831551 59.772270 54.277523
Finished Birdeye eval.
Finished 3D bounding box eval.
Your evaluation results are available at:
./saves/pixor_e2e/predicted_label_eval

**Comment by YurongYou** [comment]
Hi Wyx9352, thanks for your interest! PIXOR (https://arxiv.org/pdf/1902.06326.pdf) model only support BEV detection.

**Comment by Wyx9352** [comment]
ok! Thank you for your reply
