### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by XiangZhou1** [mileyan/pseudo-LiDAR_e2e#19]
Hi, I am interested in you work. But when I run the eval code of pseudo-LiDAR_e2e（PointRCNN ），I have encountered the following problem，could you help me? 

/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [111,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [111,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "eval_rcnn_depth.py", line 933, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn_depth.py", line 789, in eval_single_ckpt
    eval_one_epoch(model, depth_model, test_loader, epoch_id, root_result_dir, logger)
  File "eval_rcnn_depth.py", line 707, in eval_one_epoch
    ret_dict = eval_one_epoch_joint(model, depth_model, dataloader, epoch_id, result_dir, logger)
  File "eval_rcnn_depth.py", line 500, in eval_one_epoch_joint
    depth_loss, data = depth_model.eval(data, args.max_high)
  File "/media/4T/zdl/pseudo_lidar_serize/pseudo-LiDAR_e2e/PointRCNN/tools/../lib/net/depth_net.py", line 192, in eval
    cloud = transform(cloud, calib_info, sparse_type='angular_min', start=2.0)
  File "/media/4T/zdl/pseudo_lidar_serize/pseudo-LiDAR_e2e/PointRCNN/tools/../lib/net/depth_net.py", line 252, in transform
    points = nearest_sparse_angular(points, start)
  File "/media/4T/zdl/pseudo_lidar_serize/pseudo-LiDAR_e2e/PointRCNN/tools/../lib/net/depth_net.py", line 381, in nearest_sparse_angular
    sparse_points = depth_map[depth_map[:, 0] != -1.0]
RuntimeError: copy_if failed to synchronize: device-side assert triggered
eval:   0%|

**Comment by rui1996** [comment]
Hi, I guess this sort of problems mostly come from the difference of environment, like pytorch and cuda version, please refer to the readme as well as the original pointrcnn repo for assistance.

**Comment by kaixinbear** [comment]
Hi, I encountered this problem too.
It is caused by different version of torch_scatter.scatter_max returning argmax with different value(-1 or N).
The `min_dist_subsample` fucntion judges -1 only, which could be invalid for some version of scatter_max.
Just change `mask = argmin[(argmin != -1)]` to  `mask = argmin[(argmin != -1) & (argmin != N)]` would fix this issue
