### ISSUE TITLE
About code and image fusion

### ISSUE THREAD

**Issue by LJ-Zhang** [mileyan/pseudo-LiDAR_e2e#2]
Thank you for your contribution！I have several questions about the code and paper.
your code contains image-based fusion in PIXOR，which is not mentioned in the paper.
And iI wonder whether the experimental results in the paper is produced with this implementation？
Or have you tried vanilla PIXOR with the method？is it still work？

**Comment by YurongYou** [comment]
Hi LJ-Zhang,

Thanks for your interest! As mentioned in the paper, the results in the paper are generated by image-based fusion in PIXOR (PIXOR*). We found w/ image fusion the detection results (using LiDAR+image) are always better, thus we report PIXOR*'s result. We did not try vanilla PIXOR on pseudo-LiDAR, but you can try it by yourself. Thanks!
