### ISSUE TITLE
Pseudo-Lidar Generated point cloud

### ISSUE THREAD

**Issue by a-akram-98** [mileyan/pseudo-LiDAR_e2e#21]
When I Generate Point Cloud using the code provided in PointRCNN or PIXOR, the point cloud is some how distorted and the labels not aligned with objects, In PseudoLidar++, there was a gdc (I think to correct the point cloud), but in PSeudoLidar E2E, there is no such code for correction, so what is happening?, can some one help and illustrate this to me.

**Comment by rui1996** [comment]
Hi, in this paper we follow this procedure:
Stereo image -> depth map -> quantization/subsampling -> 3D detection.
I do not think we need any kind of correction, this is a pure image-based 3D object detection algorithm.
