### ISSUE TITLE
Different mAP results

### ISSUE THREAD

**Issue by a-akram-98** [mileyan/pseudo-LiDAR_e2e#23]
We used provided evaluation script and pretrained weights and results was less than provided in the paper with 5% ? and we noticed that this results was the same as the PL++, is the weights provided is PL++ or PL-E2E

```
2021-07-11 17:31:13,277   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:95.5236, 85.4079, 78.3538
bev  AP:82.0941, 62.9715, 57.2632
3d   AP:67.8891, 50.4661, 45.3872
aos  AP:94.07, 83.04, 75.91
Car AP@0.70, 0.50, 0.50:
bbox AP:95.5236, 85.4079, 78.3538
bev  AP:89.8431, 83.7960, 77.5032
3d   AP:89.6241, 78.5735, 75.0044
aos  AP:94.07, 83.04, 75.91
```

**Comment by rui1996** [comment]
Hi, the weights provided are just initialization weights but not the final weights. What you should do is load the weights and do end to end training as indicated [here](https://github.com/mileyan/pseudo-LiDAR_e2e/tree/master/PointRCNN#run-pointrcnn_pl_end2end-training-and-evaluation).
