### ISSUE TITLE
Package Version not specified

### ISSUE THREAD

**Issue by albertchristian92** [mileyan/pseudo-LiDAR_e2e#4]
Hello, thank you for your works. I am interested to try your code, but actually I got some problem during pre-installation of the dependency, especially in torch_scatter package installation. 

My problem is:
It always have a conflict regarding with incompatible issue. I already tried install the packages in separated environment using different version of Python listed below:

1. Python version 3.8
2. Python version 3.6.10
3. Python version 3.7.7
4. Python version 3.5.6

Based on this issue, may I know which version of python that you used? and can you provide the version of any packages that you used? Thank you very much and I am really appreciated for your answer.

Here is the screenshot during the installation of torch scatter in python 3.5.6:
![python35](https://user-images.githubusercontent.com/12479762/85746033-bd49bf80-b738-11ea-9048-01372e34448b.png)

**Comment by YurongYou** [comment]
Hi albertchristian92,

Thanks for your interest! We use python 3.7.3 and the version of torch-scatter is 1.4.0.
