### ISSUE TITLE
experiments with Argoverse

### ISSUE THREAD

**Issue by rvalienter90** [mileyan/pseudo-LiDAR_e2e#5]
Hi , 
This is an amazing work, congratulations on the great results! Thank you very much for sharing your all your research.
Do you plan to release your code for the experiments with Argoverse, and how you convert the Argoverse dataset into KITTI format?
Thanks!

**Comment by rui1996** [comment]
Hi we currently do not have the plan for releasing Argoverse code, but would consider doing it in the future when we have bandwidth to go back to this project.
