### ISSUE TITLE
missing Lib file in PointRCNN

### ISSUE THREAD

**Issue by czy341181** [mileyan/pseudo-LiDAR_e2e#6]
Thanks for your amazing work! I tried to run your code, but I ran into some trouble. Is the code in PointRCNN complete?

**Comment by YurongYou** [comment]
Could you provide more information about what error you got?

**Comment by czy341181** [comment]
from lib.net.point_rcnn import PointRCNN

But it seems that there is no Lib folder in your code.

**Comment by YurongYou** [comment]
@rui1996 I guess we should also include the lib folder https://github.com/sshaoshuai/PointRCNN/tree/master/lib and https://github.com/sshaoshuai/Pointnet2.PyTorch/tree/5a4416f51ceaeba242828cabf39133433336850d

**Comment by czy341181** [comment]
from lib.net.depth_Ne import Depth_model

There is depth_Net in the Lib folder, will you update the code later?

**Comment by rvalienter90** [comment]
Thanks again for your amazing work! I also had tried your previous work and was able to replicate the results. But for this pseudoLidar E2E with PointRCNN I have missing libraries too that I cannot find in original PointRCNN(https://github.com/sshaoshuai/PointRCNN/tree/master/lib) or other pseudoLidar works.
For me the files **depth_net.py** and **kitti_depth_rcnn_dataset.py** are missing (**from lib.net.depth_net import DepthModel, from lib.datasets.kitti_depth_rcnn_dataset import KittiRCNNDataset**) , your modifications/new files from PointRCNN to make E2E code work. 

Missing files
1. **depth_net.py** 
2. **kitti_depth_rcnn_dataset.py**

I appreciate your code updates / help. Thank you very much for sharing!!

**Comment by rui1996** [comment]
Hi all, sorry for making this mistake. I will update soon.

**Comment by rvalienter90** [comment]
Hi @rui1996 , thank you very much!!

**Comment by rui1996** [comment]
Hi all, it is updated. The reason for this error is in the .gitignore file in the root dir (not Pointrcnn dir), it accidentally includes 'lib/', making us missing files while uploading. Again, sorry for this.
