### ISSUE TITLE
How to get depth data

### ISSUE THREAD

**Issue by BlarkLee** [mileyan/pseudo-LiDAR_e2e#7]
Thank you for this great work! Can you please make it clear how to get depth data corresponding to the KITTI Object data? It seems that KITTI official website does not offer depth data corresponding to the KITTI Object data.

**Comment by rui1996** [comment]
Hi, would you mind checking out this:
https://github.com/mileyan/pseudo_lidar#22-download-the-dataset

**Comment by BlarkLee** [comment]
Oooh... Sorry I see, thank you so much!

**Comment by BlarkLee** [comment]
> Hi, would you mind checking out this:
> https://github.com/mileyan/pseudo_lidar#22-download-the-dataset

I see, so you are basically using lidar to generate depth info? But when I was training this end2end work, I got this error 
![image](https://user-images.githubusercontent.com/37535501/91075654-46735a80-e5f3-11ea-9ffa-a8056b53c6b9.png)
It seems that I still need to prepare depth data for training, do you have any custom application for generating depth data here in this repo?

**Comment by BlarkLee** [comment]
I mean I have packed the data as https://github.com/mileyan/pseudo_lidar#22-download-the-dataset
![image](https://user-images.githubusercontent.com/37535501/91076588-91da3880-e5f4-11ea-9a3b-f439cd6006b6.png)


But it seems that I still need to pack depth data to dept_dir together with image2, image3, calib, velodyne, label2 right? 
![image](https://user-images.githubusercontent.com/37535501/91076417-550e4180-e5f4-11ea-99dd-eb3455f56b4d.png)

**Comment by BlarkLee** [comment]
Thank you!

**Comment by a-akram-98** [comment]
@rui1996 @BlarkLee The folder provided in pseudo lidar is disparity but here in e2e model it want a ground truth depth, am I missing something !?
